version: "3"

services:

  concentratord_slot1:
    #image: concentratord:0.1
    # or comment out image: and build it yourself
    build:
      context: ./chirpstack_concentratord_sx1302_docker/
      dockerfile: ./Dockerfile
    restart: unless-stopped
    privileged: true
    volumes:
      # Mount the shared volume for the socket files
      - concentratord_sockets_slot1:/tmp/
      - ./configuration/concentratord/concentratord_RAK7391_slot1.toml:/app/concentratord.toml:ro
    networks:
      - slot_1_cloud

  mqtt_forwarder_cloud:
    #image: mqtt_forwarder:0.1
    # or comment out image: and build it yourself
    build:
      context: ./chirpstack_mqtt_forwarder_docker/
      dockerfile: ./Dockerfile
    restart: unless-stopped
    # privileged: true
    # ports:
    #   - "1700:1700/udp"
    volumes:
    # Mount the shared volume for the socket files
      - concentratord_sockets_slot1:/tmp/
      - ./configuration/chirpstack-mqtt-forwarder/chirpstack-mqtt-forwarder-cloud.toml:/app/chirpstack-mqtt-forwarder.toml:ro
    depends_on:
      - concentratord_slot1
    networks:
      - slot_1_cloud
 
  chirpstack:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      - ./lorawan-devices:/opt/lorawan-devices
    depends_on:
      - postgres
      - mosquitto
      - redis
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
    ports:
      - 8080:8080
    networks:
      - slot_2_local


  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    ports:
      - 8090:8090
    depends_on:
      - chirpstack
    networks:
      - slot_2_local

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    networks:
      - slot_2_local

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - slot_2_local

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes: 
      - ./configuration/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - slot_2_local

  

  concentratord_slot2:
    #image: concentratord:0.1
    # or comment out image: and build it yourself
    build:
      context: ./chirpstack_concentratord_sx1302_docker/
      dockerfile: ./Dockerfile
    restart: unless-stopped
    privileged: true
    volumes:
      # Mount the shared volume for the socket files
      - concentratord_sockets_slot2:/tmp/
      - ./configuration/concentratord/concentratord_RAK7391_slot2.toml:/app/concentratord.toml:ro
    networks:
      - slot_2_local

  mqtt_forwarder_local:
    #image: mqtt_forwarder:0.1
    # or comment out image: and build it yourself
    build:
      context: ./chirpstack_mqtt_forwarder_docker/
      dockerfile: ./Dockerfile
    restart: unless-stopped
    # privileged: true
    # ports:
    #   - "1700:1700/udp"
    volumes:
    # Mount the shared volume for the socket files
      - concentratord_sockets_slot2:/tmp/
      - ./configuration/chirpstack-mqtt-forwarder/chirpstack-mqtt-forwarder-local.toml:/app/chirpstack-mqtt-forwarder.toml:ro
    depends_on:
      - chirpstack
      - concentratord_slot2
    networks:
      - slot_2_local

volumes:
  postgresqldata:
  redisdata:
  concentratord_sockets_slot1:
  concentratord_sockets_slot2:

networks:
  slot_1_cloud:
  slot_2_local:
